[2025-04-23T15:48:51.834+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T15:48:51.845+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_etl_dbt.dbt_run_transformations manual__2025-04-23T15:16:33.263567+00:00 [queued]>
[2025-04-23T15:48:51.850+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_etl_dbt.dbt_run_transformations manual__2025-04-23T15:16:33.263567+00:00 [queued]>
[2025-04-23T15:48:51.851+0000] {taskinstance.py:2865} INFO - Starting attempt 3 of 3
[2025-04-23T15:48:51.859+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run_transformations> on 2025-04-23 15:16:33.263567+00:00
[2025-04-23T15:48:51.876+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=30805) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T15:48:51.878+0000] {standard_task_runner.py:72} INFO - Started process 30808 to run task
[2025-04-23T15:48:51.876+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_data_etl_dbt', 'dbt_run_transformations', 'manual__2025-04-23T15:16:33.263567+00:00', '--job-id', '71', '--raw', '--subdir', 'DAGS_FOLDER/Stock_built_ELT.py', '--cfg-path', '/tmp/tmpyquxlyrz']
[2025-04-23T15:48:51.880+0000] {standard_task_runner.py:105} INFO - Job 71: Subtask dbt_run_transformations
[2025-04-23T15:48:51.916+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_data_etl_dbt.dbt_run_transformations manual__2025-04-23T15:16:33.263567+00:00 [running]> on host 712e28762a67
[2025-04-23T15:48:51.984+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_data_etl_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T15:16:33.263567+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T15:16:33.263567+00:00'
[2025-04-23T15:48:51.985+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T15:48:51.987+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T15:48:51.989+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --select models/intermediate/moving_averages models/intermediate/rsi --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-04-23T15:48:51.996+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T15:48:55.146+0000] {subprocess.py:93} INFO - [0m15:48:55  Running with dbt=1.7.19
[2025-04-23T15:48:56.015+0000] {subprocess.py:93} INFO - [0m15:48:56  Registered adapter: snowflake=1.7.1
[2025-04-23T15:48:56.037+0000] {subprocess.py:93} INFO - [0m15:48:56  Unable to do partial parsing because of a version mismatch
[2025-04-23T15:48:57.236+0000] {subprocess.py:93} INFO - [0m15:48:57  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-23T15:48:57.237+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-04-23T15:48:57.237+0000] {subprocess.py:93} INFO - - models.stock_data_transform_dbt.marts
[2025-04-23T15:48:57.263+0000] {subprocess.py:93} INFO - [0m15:48:57  Found 4 models, 1 snapshot, 1 source, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models
[2025-04-23T15:48:57.266+0000] {subprocess.py:93} INFO - [0m15:48:57  The selection criterion 'models/intermediate/moving_averages' does not match any nodes
[2025-04-23T15:48:57.268+0000] {subprocess.py:93} INFO - [0m15:48:57  The selection criterion 'models/intermediate/rsi' does not match any nodes
[2025-04-23T15:48:57.269+0000] {subprocess.py:93} INFO - [0m15:48:57
[2025-04-23T15:48:57.269+0000] {subprocess.py:93} INFO - [0m15:48:57  Nothing to do. Try checking your model configs and model specification args
[2025-04-23T15:48:58.065+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-23T15:48:58.112+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T15:48:58.113+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_data_etl_dbt, task_id=dbt_run_transformations, run_id=manual__2025-04-23T15:16:33.263567+00:00, execution_date=20250423T151633, start_date=20250423T154851, end_date=20250423T154858
[2025-04-23T15:48:58.167+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T15:48:58.195+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T15:48:58.197+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
