[2025-04-23T15:30:43.337+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-23T15:30:43.348+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: stock_data_etl_dbt.dbt_run_transformations manual__2025-04-23T15:16:33.263567+00:00 [queued]>
[2025-04-23T15:30:43.354+0000] {taskinstance.py:2612} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: stock_data_etl_dbt.dbt_run_transformations manual__2025-04-23T15:16:33.263567+00:00 [queued]>
[2025-04-23T15:30:43.354+0000] {taskinstance.py:2865} INFO - Starting attempt 2 of 2
[2025-04-23T15:30:43.362+0000] {taskinstance.py:2888} INFO - Executing <Task(BashOperator): dbt_run_transformations> on 2025-04-23 15:16:33.263567+00:00
[2025-04-23T15:30:43.372+0000] {logging_mixin.py:190} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70 DeprecationWarning: This process (pid=28583) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-04-23T15:30:43.375+0000] {standard_task_runner.py:72} INFO - Started process 28586 to run task
[2025-04-23T15:30:43.372+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'stock_data_etl_dbt', 'dbt_run_transformations', 'manual__2025-04-23T15:16:33.263567+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/Stock_built_ELT.py', '--cfg-path', '/tmp/tmpw6ht4e5k']
[2025-04-23T15:30:43.376+0000] {standard_task_runner.py:105} INFO - Job 68: Subtask dbt_run_transformations
[2025-04-23T15:30:43.435+0000] {task_command.py:467} INFO - Running <TaskInstance: stock_data_etl_dbt.dbt_run_transformations manual__2025-04-23T15:16:33.263567+00:00 [running]> on host 712e28762a67
[2025-04-23T15:30:43.542+0000] {taskinstance.py:3131} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='stock_data_etl_dbt' AIRFLOW_CTX_TASK_ID='dbt_run_transformations' AIRFLOW_CTX_EXECUTION_DATE='2025-04-23T15:16:33.263567+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-23T15:16:33.263567+00:00'
[2025-04-23T15:30:43.544+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-04-23T15:30:43.547+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-23T15:30:43.549+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '/home/***/.local/bin/dbt run --select models/intermediate/moving_averages models/intermediate/rsi --profiles-dir /opt/***/dbt --project-dir /opt/***/dbt']
[2025-04-23T15:30:43.567+0000] {subprocess.py:86} INFO - Output:
[2025-04-23T15:30:46.296+0000] {subprocess.py:93} INFO - [0m15:30:46  Running with dbt=1.7.19
[2025-04-23T15:30:47.221+0000] {subprocess.py:93} INFO - [0m15:30:47  Registered adapter: snowflake=1.7.1
[2025-04-23T15:30:47.393+0000] {subprocess.py:93} INFO - [0m15:30:47  [[33mWARNING[0m]: Configuration paths exist in your dbt_project.yml file which do not apply to any resources.
[2025-04-23T15:30:47.394+0000] {subprocess.py:93} INFO - There are 1 unused configuration paths:
[2025-04-23T15:30:47.395+0000] {subprocess.py:93} INFO - - models.stock_data_transform_dbt.marts
[2025-04-23T15:30:47.413+0000] {subprocess.py:93} INFO - [0m15:30:47  Found 4 models, 1 snapshot, 1 source, 0 exposures, 0 metrics, 430 macros, 0 groups, 0 semantic models
[2025-04-23T15:30:47.415+0000] {subprocess.py:93} INFO - [0m15:30:47  The selection criterion 'models/intermediate/moving_averages' does not match any nodes
[2025-04-23T15:30:47.417+0000] {subprocess.py:93} INFO - [0m15:30:47  The selection criterion 'models/intermediate/rsi' does not match any nodes
[2025-04-23T15:30:47.418+0000] {subprocess.py:93} INFO - [0m15:30:47
[2025-04-23T15:30:47.419+0000] {subprocess.py:93} INFO - [0m15:30:47  Nothing to do. Try checking your model configs and model specification args
[2025-04-23T15:30:48.232+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2025-04-23T15:30:48.301+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-04-23T15:30:48.302+0000] {taskinstance.py:352} INFO - Marking task as SUCCESS. dag_id=stock_data_etl_dbt, task_id=dbt_run_transformations, run_id=manual__2025-04-23T15:16:33.263567+00:00, execution_date=20250423T151633, start_date=20250423T153043, end_date=20250423T153048
[2025-04-23T15:30:48.347+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-23T15:30:48.389+0000] {standard_task_runner.py:217} INFO - Process not found (most likely exited), stop collecting metrics
[2025-04-23T15:30:48.411+0000] {taskinstance.py:3900} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-04-23T15:30:48.412+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
